const { ROLES } = require('./roles');
const { PERMISSIONS } = require('./permissions');

const PERMISSION_ROLES = {
  [PERMISSIONS.VIEW_DATA]: [
    ROLES.VIEWER,
    ROLES.MANAGER,
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.BUY_CREDITS]: [
    ROLES.MANAGER,
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.SELL_CREDITS]: [
    ROLES.MANAGER,
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.RETIRE_CREDITS]: [
    ROLES.MANAGER,
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.TRANSFER_CREDITS]: [
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.CREATE_LISTING]: [
    ROLES.MANAGER,
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.EDIT_LISTING]: [
    ROLES.MANAGER,
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.CANCEL_LISTING]: [
    ROLES.MANAGER,
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.INVITE_USER]: [
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.REMOVE_USER]: [
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.ASSIGN_ROLE]: [
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.MANAGE_ADMINS]: [
    ROLES.SUPERADMIN,
  ],

  [PERMISSIONS.UPDATE_ORG]: [
    ROLES.ADMIN,
    ROLES.SUPERADMIN,
  ],
};

module.exports = { PERMISSION_ROLES };
